version: "3.8"
services:
    app:
        build: ./docker/php
        container_name: cms-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - cms

    postgres:
        image: postgres:13-alpine
        container_name: cms-postgres
        restart: unless-stopped
        volumes:
            - "cmsDBData:/var/lib/postgresql/data"
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        ports:
            - "5442:5432"
        networks:
            - cms

    nginx:
        image: nginx:alpine
        container_name: cms-nginx
        restart: unless-stopped
        working_dir: /var/www/
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
            - ./var/log/nginx:/var/log/nginx
        networks:
            - cms

networks:
    cms:
        driver: bridge

volumes:
    cmsDBData:
